const getAvatarUrl = (name, bg = 'EEF2FF', color = '1D4ED8') =>
  `https://ui-avatars.com/api/?name=${encodeURIComponent(name)}&background=${bg}&color=${color}`;

export const INVITATION_TABS = [
  { key: 'new', label: 'New Invitations' },
  { key: 'accepted', label: 'Accepted' },
  { key: 'declined', label: 'Declined' },
];

export const INVITATION_FILTER_OPTIONS = [
  { key: 'all', label: 'All work modes' },
  { key: 'remote', label: 'Remote' },
  { key: 'hybrid', label: 'Hybrid' },
  { key: 'on-site', label: 'On-site' },
];

export const INVITATION_SORT_OPTIONS = [
  { key: 'newest', label: 'Newest first' },
  { key: 'oldest', label: 'Oldest first' },
  { key: 'match-desc', label: 'Highest AI match' },
];

export const MOCK_INVITATIONS = [
  {
    id: 101,
    jobId: 21,
    title: 'Senior React Developer',
    company: 'TechFlow Systems',
    companyLogo: getAvatarUrl('TechFlow Systems', 'DBEAFE', '1D4ED8'),
    recruiterName: 'Sarah Smith',
    recruiterRole: 'HR Manager',
    recruiterAvatar: getAvatarUrl('Sarah Smith', 'F3E8FF', '7E22CE'),
    message:
      "Hi Dang, I was impressed by your profile, especially your experience with scalable dashboards. We'd love to chat about a lead role opening up next week.",
    aiMatch: 98,
    salaryText: '$120k - $150k / year',
    locationText: 'Remote (US/Canada)',
    workMode: 'remote',
    employmentType: 'Full-time',
    receivedAt: '2026-03-03T07:20:00.000Z',
    status: 'new',
  },
  {
    id: 102,
    jobId: 34,
    title: 'Lead Product Designer',
    company: 'Nova Creative',
    companyLogo: getAvatarUrl('Nova Creative', 'E0E7FF', '4338CA'),
    recruiterName: 'Mike Ross',
    recruiterRole: 'Talent Acquisition',
    recruiterAvatar: getAvatarUrl('Mike Ross', 'DBEAFE', '1D4ED8'),
    message:
      'We are looking for someone with your exact skill set in Figma and user research. Our design team is growing fast and we need a leader.',
    aiMatch: 92,
    salaryText: '$95k - $115k / year',
    locationText: 'New York, NY',
    workMode: 'hybrid',
    employmentType: 'Hybrid',
    receivedAt: '2026-03-02T13:10:00.000Z',
    status: 'new',
  },
  {
    id: 103,
    jobId: 45,
    title: 'Backend Engineer (Go)',
    company: 'StreamLine Data',
    companyLogo: getAvatarUrl('StreamLine Data', 'FEF3C7', '92400E'),
    recruiterName: 'David Chen',
    recruiterRole: 'CTO',
    recruiterAvatar: getAvatarUrl('David Chen', 'FEE2E2', 'B91C1C'),
    message:
      "Saw your open-source contributions on event-driven systems. We use a similar architecture and think you'd be a great fit for our platform team.",
    aiMatch: 75,
    salaryText: '$130k - $160k / year',
    locationText: 'San Francisco, CA',
    workMode: 'on-site',
    employmentType: 'On-site',
    receivedAt: '2026-03-01T09:45:00.000Z',
    status: 'new',
  },
  {
    id: 104,
    jobId: 52,
    title: 'Full-stack Engineer',
    company: 'Vertex Cloud',
    companyLogo: getAvatarUrl('Vertex Cloud', 'DCFCE7', '166534'),
    recruiterName: 'Emily Johnson',
    recruiterRole: 'Recruitment Lead',
    recruiterAvatar: getAvatarUrl('Emily Johnson', 'FCE7F3', '9D174D'),
    message:
      'Your profile aligns very well with our SaaS roadmap. We would like to schedule an interview with the engineering manager this week.',
    aiMatch: 90,
    salaryText: '$110k - $135k / year',
    locationText: 'Remote (APAC)',
    workMode: 'remote',
    employmentType: 'Full-time',
    receivedAt: '2026-02-27T05:20:00.000Z',
    status: 'accepted',
  },
  {
    id: 105,
    jobId: 66,
    title: 'Data Analyst',
    company: 'Insight Loop',
    companyLogo: getAvatarUrl('Insight Loop', 'FCE7F3', 'BE185D'),
    recruiterName: 'Priya Kapoor',
    recruiterRole: 'People Partner',
    recruiterAvatar: getAvatarUrl('Priya Kapoor', 'E0F2FE', '0369A1'),
    message:
      'We liked your data storytelling portfolio and practical SQL assessments. This role partners closely with product and growth teams.',
    aiMatch: 84,
    salaryText: '$70k - $90k / year',
    locationText: 'Austin, TX',
    workMode: 'hybrid',
    employmentType: 'Hybrid',
    receivedAt: '2026-02-25T11:30:00.000Z',
    status: 'declined',
  },
  {
    id: 106,
    jobId: 72,
    title: 'Product Manager',
    company: 'Orbit Works',
    companyLogo: getAvatarUrl('Orbit Works', 'EDE9FE', '5B21B6'),
    recruiterName: 'James Lee',
    recruiterRole: 'Hiring Manager',
    recruiterAvatar: getAvatarUrl('James Lee', 'F3F4F6', '111827'),
    message:
      'Your cross-functional delivery record stood out. We want someone who can own roadmap planning for our collaboration suite.',
    aiMatch: 88,
    salaryText: '$105k - $140k / year',
    locationText: 'Seattle, WA',
    workMode: 'on-site',
    employmentType: 'Full-time',
    receivedAt: '2026-02-23T08:00:00.000Z',
    status: 'accepted',
  },
  {
    id: 107,
    jobId: 88,
    title: 'QA Automation Engineer',
    company: 'QualiTest Hub',
    companyLogo: getAvatarUrl('QualiTest Hub', 'DBEAFE', '1E40AF'),
    recruiterName: 'Olivia Tran',
    recruiterRole: 'Technical Recruiter',
    recruiterAvatar: getAvatarUrl('Olivia Tran', 'FEF9C3', 'A16207'),
    message:
      'We have a strong automation culture and thought your Cypress and Playwright background could be a strong match for the team.',
    aiMatch: 80,
    salaryText: '$85k - $110k / year',
    locationText: 'Remote (Global)',
    workMode: 'remote',
    employmentType: 'Full-time',
    receivedAt: '2026-02-20T15:40:00.000Z',
    status: 'declined',
  },
  {
    id: 108,
    jobId: 91,
    title: 'Mobile Engineer (React Native)',
    company: 'Pulse Mobile',
    companyLogo: getAvatarUrl('Pulse Mobile', 'F0F9FF', '0C4A6E'),
    recruiterName: 'Anita Gomez',
    recruiterRole: 'Senior Recruiter',
    recruiterAvatar: getAvatarUrl('Anita Gomez', 'ECFDF5', '047857'),
    message:
      'Our team is launching two consumer apps this quarter and your mobile architecture experience is exactly what we need.',
    aiMatch: 93,
    salaryText: '$100k - $128k / year',
    locationText: 'Toronto, ON',
    workMode: 'remote',
    employmentType: 'Full-time',
    receivedAt: '2026-03-02T04:50:00.000Z',
    status: 'new',
  },
  {
    id: 109,
    jobId: 95,
    title: 'AI Engineer',
    company: 'Cortex Labs',
    companyLogo: getAvatarUrl('Cortex Labs', 'F5F3FF', '6D28D9'),
    recruiterName: 'Liam Walker',
    recruiterRole: 'Head of AI',
    recruiterAvatar: getAvatarUrl('Liam Walker', 'F1F5F9', '334155'),
    message:
      'We are building retrieval and evaluation pipelines. Your practical LLM integration projects are aligned with our roadmap.',
    aiMatch: 95,
    salaryText: '$140k - $180k / year',
    locationText: 'Boston, MA',
    workMode: 'hybrid',
    employmentType: 'Hybrid',
    receivedAt: '2026-02-18T07:25:00.000Z',
    status: 'accepted',
  },
];
