export const APPLICATION_ERROR_CODE = {
    MAX_APPLY_ATTEMPTS_REACHED: "MAX_APPLY_ATTEMPTS_REACHED",
    ALREADY_REJECTED_FOR_THIS_JOB: "ALREADY_REJECTED_FOR_THIS_JOB",
    CANNOT_REAPPLY_AFTER_PROCESSING: "CANNOT_REAPPLY_AFTER_PROCESSING",
    REQUIRED_QUESTION_NOT_ANSWERED: "REQUIRED_QUESTION_NOT_ANSWERED",
    RESUME_STILL_PARSING: "RESUME_STILL_PARSING",
    RESUME_PARSE_FAILED: "RESUME_PARSE_FAILED",
    RESUME_ALREADY_DELETED: "RESUME_ALREADY_DELETED",
    NOT_HAVE_PERMISSION: "NOT_HAVE_PERMISSION"
};
