export const APPLICATION_ERROR_CODE = {
    MAX_APPLY_ATTEMPTS_REACHED: "MAX_APPLY_ATTEMPTS_REACHED",
    ALREADY_REJECTED_FOR_THIS_JOB: "ALREADY_REJECTED_FOR_THIS_JOB",
    CANNOT_REAPPLY_AFTER_PROCESSING: "CANNOT_REAPPLY_AFTER_PROCESSING",
    REQUIRED_QUESTION_NOT_ANSWERED: "REQUIRED_QUESTION_NOT_ANSWERED",
    RESUME_STILL_PARSING: "RESUME_STILL_PARSING",
    RESUME_PARSE_FAILED: "RESUME_PARSE_FAILED",
    RESUME_ALREADY_DELETED: "RESUME_ALREADY_DELETED",
    NOT_HAVE_PERMISSION: "NOT_HAVE_PERMISSION"
};

export const APPLICATION_STATUS = {
    APPLIED: "APPLIED",
    VIEWED: "VIEWED",
    SHORTLISTED: "SHORTLISTED",
    AUTO_REJECTED: "AUTO_REJECTED",
    NOT_SUITABLE: "NOT_SUITABLE"
};

export const APPLICATION_STATUS_LABEL = {
    [APPLICATION_STATUS.APPLIED]: "Applied",
    [APPLICATION_STATUS.VIEWED]: "Employer Viewed",
    [APPLICATION_STATUS.SHORTLISTED]: "Employer Viewed",
    [APPLICATION_STATUS.AUTO_REJECTED]: "Auto Rejected",
    [APPLICATION_STATUS.NOT_SUITABLE]: "Not Suitable"
};

